//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto01.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adiccion_Usuario
    {
        public int Id { get; set; }
        public Nullable<int> Cod_Adiccion { get; set; }
        public Nullable<int> Cod_Usuario { get; set; }
    
        public virtual Adiccion Adiccion { get; set; }
        public virtual Adiccion Adiccion1 { get; set; }
        public virtual Adiccion Adiccion2 { get; set; }
        public virtual Adiccion Adiccion3 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual Usuario Usuario3 { get; set; }
    }
}
