//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNuevoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adiccion
    {
        public Adiccion()
        {
            this.Adiccion_Usuario = new HashSet<Adiccion_Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Adiccion_Usuario> Adiccion_Usuario { get; set; }
    }
}
