//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNuevoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adiccion_Usuario
    {
        public int Id { get; set; }
        public Nullable<int> Cod_Adiccion { get; set; }
        public Nullable<int> Cod_Usuario { get; set; }
    
        public virtual Adiccion Adiccion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
