//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNuevoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobertura_Poliza
    {
        public Cobertura_Poliza()
        {
            this.Registro_Poliza = new HashSet<Registro_Poliza>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Porcentaje { get; set; }
    
        public virtual ICollection<Registro_Poliza> Registro_Poliza { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
