//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNuevoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Poliza
    {
        public int Id { get; set; }
        public Nullable<double> Monto_Asegurado { get; set; }
        public Nullable<double> Prima_Impuesto { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Porcentaje_Cobertura { get; set; }
        public Nullable<int> Numero_Adiccion { get; set; }
        public Nullable<double> Monto_Adiccion { get; set; }
        public Nullable<double> Prima_Final { get; set; }
        public Nullable<int> Cod_Cobertura_Poliza { get; set; }
        public Nullable<int> Cod_Cliente { get; set; }
        public Nullable<int> Cod_Tipo_Poliza { get; set; }
    
        public virtual Cobertura_Poliza Cobertura_Poliza { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Tipo_Poliza Tipo_Poliza { get; set; }
    }
}
