//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNuevoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Adiccion_Usuario = new HashSet<Adiccion_Usuario>();
            this.Registro_Poliza = new HashSet<Registro_Poliza>();
        }
    
        public int Id { get; set; }
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Telefono1 { get; set; }
        public Nullable<int> Telefono2 { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Cod_Tipo_Usuario { get; set; }
        public Nullable<int> Cod_Cobertura_Poliza { get; set; }
        public string Alias_Usuario { get; set; }
        public string Pass_Usuario { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Adiccion_Usuario> Adiccion_Usuario { get; set; }
        public virtual Cobertura_Poliza Cobertura_Poliza { get; set; }
        public virtual ICollection<Registro_Poliza> Registro_Poliza { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
